### ISSUE TITLE
Separação de minorias

### ISSUE THREAD

**Issue by onhernandes** [Caaddss/awesome-live-coding-streams#9]
Fiquei curioso, vi que existem dois arquivos com links do Twitch de pessoas de minorias e outro geral. É necessário separar assim? 

Não seria mais fácil juntar tudo num arquivo só, e só apontar em cada pessoa, qual minoria faz parte?

Como sugestão, tem as tabelas do Markdown, acho que podem ajudar.

**Comment by Caaddss** [comment]
É sim, pq aparentemente pra Twitch é muito dificil procurar minorias no meio do geral

A lista geral tem as minorias tbm...mas a separação foi pra chamar atenção e n ter como ngm falar que foi dificil achar
